exclude: '^docs/conf.py'
exclude: '^docs/developer-environment/src/.ssh/totalgood_openchat.pem'
exclude: '^docs/developer-environment/src/.ssh/imagecanopykey.pem'

repos:
- repo: git://github.com/pre-commit/pre-commit-hooks
  rev: v2.1.0
  hooks:
  - id: trailing-whitespace
  - id: check-added-large-files
  - id: check-ast
  - id: check-json
  - id: check-merge-conflict
  - id: check-xml
  - id: check-yaml
  - id: debug-statements
  - id: end-of-file-fixer
  - id: requirements-txt-fixer
  - id: mixed-line-ending
    args: ['--fix=no']
  - id: flake8
    args: ["--max-line-length=150", "--ignore=E266,E226,E302,E41", "--append-config=~/.config/flake8", "--append-config=.flake8"]

# this keeps deleting blank lines between imports and code
# - repo: https://github.com/pre-commit/mirrors-isort
#   rev: v4.3.15
#   hooks:
#   - id: isort
